before_script:
  - gem install dpl

stages:
  - deploy-develop
  - deploy-production

deploy-develop:
  stage: deploy-develop
  script:
    - dpl --provider=heroku --app=$HEROKU_DEVELOP_APP --api-key=$HEROKU_API_KEY
  only:
    - develop

deploy-production:
  stage: deploy-production
  script:
    - dpl --provider=heroku --app=$HEROKU_PRODUCTION_APP --api-key=$HEROKU_API_KEY
  only:
    - master
